"""Event and result-table schemas for the direct-star diagnostic."""

from __future__ import annotations

EPISODE_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "episode_seed",
    "status",
    "step_count",
    "total_reward",
    "terminated",
    "truncated",
    "goal_reached",
    "target_hit",
    "blocked_reason",
)

STEP_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "step_index",
    "source_state",
    "action_index",
    "target_state",
    "reward",
    "terminated",
    "truncated",
    "valid_transition",
    "invalid_move",
    "self_transition",
    "valid_clipped_self_transition",
    "lift_status",
)

CONTROLLER_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "step_index",
    "tier",
    "state_cell_id",
    "action_cell_id",
    "action_index",
    "selection_mode",
    "q_value_before",
)

GUARD_EVENT_FIELDS = (
    "run_id",
    "pair_id",
    "episode_index",
    "replicate_index",
    "step_index",
    "arm_id",
    "arm_type",
    "guard_type",
    "state_id",
    "available_action_count_before_guard",
    "available_action_count_after_guard",
    "guarded_action_count",
    "invalid_guard_filtered_count",
    "self_loop_guard_filtered_count",
    "all_actions_filtered_count",
    "guard_fallback_used",
    "chosen_action",
    "chosen_action_would_have_been_invalid",
    "chosen_action_would_have_been_self_loop",
    "chosen_action_transition_was_invalid",
    "chosen_action_transition_was_self_loop",
    "chosen_action_transition_was_valid_clipped_self_loop",
    "next_state_id",
    "reward",
    "done",
    "information_mode",
)

LEARNER_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "step_index",
    "learner_state_key",
    "learner_action_key",
    "reward",
    "next_state_best_value",
    "td_error",
    "old_value",
    "new_value",
    "update_applied",
)

LIFT_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "step_index",
    "tier",
    "state_cell_id",
    "action_cell_id",
    "candidate_lift_count",
    "executable_lift_count",
    "selected_lift_source",
    "selected_lift_target",
    "selected_action_index",
    "lift_status",
    "failure_reason",
)

TIER_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "replicate_index",
    "episode_index",
    "step_index",
    "tier_before",
    "tier_after",
    "state_cell_before",
    "state_cell_after",
    "active_action_cell_count",
    "blocked_reason",
)

TIMING_FIELDS = (
    "pair_id",
    "arm_id",
    "arm_type",
    "guard_type",
    "candidate_id",
    "schema_id",
    "run_id",
    "segment_name",
    "duration_seconds",
)

