"""CSV schemas for Warehouse full-state policy comparison artifacts."""

RUN_INDEX_FIELDNAMES = (
    "run_id",
    "arm_id",
    "replicate_index",
    "schema_seed",
    "seed",
    "policy_id",
    "model_family_id",
    "status",
    "artifact_root",
)

EPISODE_FIELDNAMES = (
    "run_id",
    "arm_id",
    "replicate_index",
    "schema_seed",
    "episode_index",
    "status",
    "failure_reason",
    "total_reward",
    "initial_correct_box_count",
    "final_correct_box_count",
    "initial_correct_robot_count",
    "final_correct_robot_count",
    "terminal_success",
    "terminated",
    "truncated",
    "selected_step_count",
    "valid_selected_step_count",
    "invalid_selected_step_count",
    "policy_update_count",
    "non_noop_update_count",
    "projection_attempt_count",
)

STEP_FIELDNAMES = (
    "run_id",
    "arm_id",
    "replicate_index",
    "schema_seed",
    "episode_index",
    "step_index",
    "state_id",
    "selected_action_id",
    "selected_action_vector_hash",
    "selected_action_summary",
    "valid",
    "reward",
    "terminated",
    "truncated",
    "next_state_id",
    "correct_box_count",
    "correct_robot_count",
    "invalid_reasons",
)

POLICY_DECISION_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "second",
    "policy_id",
    "model_family_id",
    "raw_action_vector_hash",
    "selected_action_vector_hash",
    "raw_valid",
    "selected_valid",
    "projection_attempt_count",
    "projection_strategy_id",
    "prior_signal_used",
    "tier",
    "tier_state_id",
    "decision_score_summary",
)

POLICY_UPDATE_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "policy_id",
    "model_family_id",
    "parameter_state_hash_before",
    "parameter_state_hash_after",
    "update_norm_or_change_count",
    "non_noop_update",
    "reward_signal_used",
    "progress_signal_used",
)

MASK_PROJECTION_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "projection_strategy_id",
    "projection_attempt_budget",
    "projection_attempt_count",
    "raw_valid",
    "selected_valid",
    "fallback_used",
    "invalid_reasons_seen",
    "selected_reason",
    "successor_out_count_used_for_selection",
)

NO_LOOKAHEAD_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "selected_action_id",
    "successor_state_id",
    "successor_out_count_observed",
    "successor_out_scope",
    "successor_out_count_used_for_selection",
    "selection_policy_id",
    "selection_policy_description",
)

TOWER_LIFT_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "downstairs_state_id",
    "tier",
    "state_cell_id",
    "fiber_candidate_count",
    "live_lift_candidate_count",
    "dead_lift_candidate_count",
    "selected_lift_state_id",
    "selected_lift_out_count",
    "lift_failure",
    "failure_reason",
    "out_scope",
    "lift_policy_id",
)

TOWER_POLICY_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "tier",
    "state_cell_id",
    "policy_id",
    "model_family_id",
    "candidate_count",
    "selected_tower_action_id",
    "selected_concrete_action_id",
    "selection_score",
    "selection_surface",
    "learning_key_surface",
)

TOWER_REALIZATION_FIELDNAMES = (
    "run_id",
    "arm_id",
    "episode_index",
    "step_index",
    "tier",
    "state_cell_id",
    "selected_tower_action_id",
    "selected_concrete_action_id",
    "selected_concrete_action_vector_hash",
    "action_realization_candidate_count",
    "concrete_selected_valid",
)

TOWER_SHAPE_FIELDNAMES = (
    "run_id",
    "schema_seed",
    "schema_id",
    "schema_mode",
    "ratio_numerator",
    "ratio_denominator",
    "max_iterations",
    "tier_count",
    "tier",
    "state_cell_count",
    "action_cell_count",
    "valid_edge_count",
    "surface_scope",
    "complete_full_action_surface",
)

TIMING_FIELDNAMES = (
    "run_id",
    "arm_id",
    "segment",
    "duration_seconds",
)
